# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # Define environment variables here
      PRODUCCION: "AWS"
      POSTGRESS_NAME: ${{ secrets.POSTGRESS_NAME }}
      POSTGRESS_URL: ${{ secrets.POSTGRESS_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hola Mundo!!

      - name: Mostrar la variable de entorno
        run: echo "La variable de entorno es ${{ env.PRODUCCION }}"
      - name: Mostrar las variables de entorno de Postgres
        run: |
          echo "El nombre de la base de datos es ${{ env.POSTGRESS_NAME }}"
          echo "La URL de la base de datos es ${{ env.POSTGRESS_URL }}"
      - name: cargar variables
        if: ${{ vars.PRODUCCION != 'AWS' }}
        run: echo "no hicimos un deploy a AWS"
